image: node:lts

stages:
    - build-nest
    - deploy-dev
before_script:
    - npm install --silent

build-nest:
    stage: build-nest
    script:
        - npm run webpack
    artifacts:
        paths:
            - dist

deploy-dev:
    image: ubuntu:latest
    stage: deply-dev
    script:
        - scp -o StrictHostKeyChecking=no -r dist $dev_server_user@$dev_server_ip:/home/Camail/back
        - ssh -o StrictHostKeyChecking=no $dev_server_user@$dev_server_ip pm2 delete server
        - ssh -o StrictHostKeyChecking=no $dev_server_user@$dev_server_ip pm2 start /home/Camail/back/dist/server.js